name: Sync Fork

on:
  schedule:
    - cron: '0 7 * * *' # at 7 am. every day
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4.2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: craigary
          base: main
          head: main
          auto_approve: true
